PAVIMENTO	EQU	P1
PULSOS		EQU	R0	; 1=UP E 0=DOWN
DESTINO		EQU	R7

ORG 00H
LJMP INICIO

ORG 000BH		; INTERRUPÇAO DO TIMER 0
RETI
LJMP TIMER0		; SUB-ROTINA QUE PROCESSA O ESTOURO DE UMA CONTAGEM

ORG 30H
INICIO: 	MOV PAVIMENTO, #01	; COMEÇA COM O ELEVADOR NO ANDAR 1
		MOV IE, #82H	; HABILITA A INTERRUPÇÃO PELO TIMER 0
		MOV IP, #02H	; COLOCA PRIORIDADE NA INTERRUPÇÃO COM TIMER 0
		MOV TMOD, #01H	; TIMER ZERO EM MODO 1
		MOV TCON, #00H	; NÃO HÁ BITS DE INTERESSE
PAVIMENTO8:	MOV DESTINO, #80H	; DESTINA O PAVIMENTO 8
M_UP:		LCALL ATRASO	; DELAY 5S
		LCALL LED	; ATUALIZA INDICADOR
		MOV A, PAVIMENTO
		MOV B, DESTINO
		CJNE A, B, M_UP		; LOOP ATÉ O DESTINO
PRIVATIVO:	MOV DESTINO, #01H	; DESTINA O PRIVATIVO
M_DOWN:		LCALL ATRASO
		LCALL LED
		MOV A, PAVIMENTO
		MOV B, DESTINO
		CJNE A, B, M_DOWN	; LOOP ATÉ O DESTINO
		LJMP PAVIMENTO8
		
ATRASO: 	MOV PULSOS, #72
		SETB TR0		; DISPARA CONTAGEM
V3:		MOV TH0, #05H
		MOV TL0, #0FFH
		JNB TF0,$
		CLR TF0
		DJNZ PULSOS,V3		; VERIFICA 72 CONTAGENS DE 69.44ms
		CLR TR0			; DESABILITA CONTAGEM
		RET

; ======== SUBROTINA PARA MOVIMENTAR O LED ========
LED: 		MOV A, PAVIMENTO	; VERIFICA SE JA CHEGOU NO DESTINO
		MOV B, DESTINO
		CJNE A, B, TRATAMENTO
		RET

TRATAMENTO:	MOV B, DESTINO		; DETERMINA QUAL O SENTIDO DA MOVIMENTAÇÃO
		MOV A, PAVIMENTO
		SUBB A, B		; COMPARA COM A POSIÇÃO ATUAL
		JNB C, L_DOWN		; C=0 DESTINO < PAVIMENTO ATUAL
		CLR C			; LIMPA A FLAG PARA PROXIMOS TRATAMENTOS

L_UP:		MOV A, PAVIMENTO
		RL A			; ATUALIZA O PAVIMENTO
		JMP F5

L_DOWN:		MOV A, PAVIMENTO
		RR A			; ATUALIZA O PAVIMENTO

F5:		MOV PAVIMENTO, A
		RET

END