ORG 00H
SJMP SETUP

ORG 13H
		LCALL MOTOR_ON		; LIGA O MOTOR CC
		LCALL DELAY		; ESPERA 1 MINUTO
		LCALL MOTOR_OFF		; DESLIGA O NOTOR
		RETI			; RETORNA DA INTERRUPÇÃO

; =========== SUBROTINA PARA CONFIGURAR OS PERIFERICOS =============
ORG 30H
SETUP: 		MOV P2, #00H	; INICIALIZA O MOTOR CC PARADO
		MOV IE, #84H	; EA = 1, EX1 = 1
		MOV TCON, #04H	; IT1 = 1 INTERRUPÇÕES POR TRANSIÇÃO
		MOV TMOD, #10H	; TIMER 1 MODO 1 (M10=0 M00=1)

MAIN: 		SJMP $		; ESPERA AS INTERRUPÇÕES

; =========== SUBROTINA DE ACIONAMENTO DO MOTOR ====================
MOTOR_ON:	SETB P2.6	; ACIONA O MOTOR CC PELOS BITS P2.6 E P2.7
		CLR P2.7
		RET

MOTOR_OFF:	CLR P2.6	; DESLIGA O MOTOR CC PELOS BITS P2.6 E P2.7
		CLR P2.7
		RET

; =========== SUBROTINA DE ATRASO ==================================
DELAY:		MOV R0, #6
RECARGA_1:	MOV R1, #144
		SETB TR1		; DISPARA CONTAGEM
RECARGA_2:	MOV TH1, #05H		; RECARRREGA O TIMER
		MOV TL1, #0FFH
		JNB TF1, $		; DT= 69.4444444442 MS
		CLR TF1
		DJNZ R1, RECARGA_2	; 144 CONTAGENS DE DT = 10 S
		DJNZ R0, RECARGA_1	; 6 CONTAGENS DE 10 S = 60 S
		CLR TR1
		RET
END