ORG 00H
SJMP SETUP

ORG 03H
MOV DPTR, #EXT0
LCALL SERIAL_WR
RETI

ORG 13H
MOV DPTR, #EXT1
LCALL SERIAL_WR
RETI

; =========== SUBROTINA PARA CONFIGURAR OS PERIFERICOS =============
ORG 30H
SETUP: 		MOV TMOD, #20H		; COLOCA O TIMER 1 EM MODO 2
		MOV TH1, #0FAH		; VALOR DE RECARGA PARA 4800 BITS/S
		MOV IE, #85H		; HABILITA AS INTERRUPÇÕES EXTERNAS 1 E 0
		MOV TCON, #05H		; IT1 = 0 IT0 = 0 INTERRUPÇÕES POR TRANSIÇÃO
		MOV SCON, #50H		; SERIAL MODO 1 (SM0=0 SM1=1) E REN=1
		SETB TR1		; DISPARA A CONTAGEM DO TIMER 1

MAIN:		SJMP $			; ESPERA AS INTERRUPÇÕES



; =========== SUBROTINA PARA ENVIO DE MENSAGENS ====================
SERIAL_WR:	MOV R2, #0
NEXT:		MOV A, R2
		MOVC A, @A+DPTR
		CJNE A, #0FFH, SEND	; DETECTA O CARACTER DE FINAL DE TEXTO
		RET

SEND:		MOV SBUF, A		; INICIA A TRANSMISSÃO DO CARACTER
		JNB TI, $		; AGUARDA TRANSMISSÃO
		CLR TI			; LIMPA FLAG DE TRANSMISSÃO PARA O PROXIMO DADO
		INC R2
		SJMP NEXT		; VAI PARA O PROXIMO MARACTER DA MENSAGEM

; ============ MENSAGENS A SER ENVIADAS =============================
EXT0:	DB 'INTERRUPCAO EXTERNA 0 ACIONADA',0DH, 0FFH
EXT1:	DB 'INTERRUPCAO EXTERNA 0 ACIONADA', 0DH, 0FFH
END