ORG 00H
SJMP SETUP

ORG 23H
LJMP SERIAL

; =========== SUBROTINA PARA CONFIGURAR OS PERIFERICOS =============
ORG 30H
SETUP: 		CLR P2.7		; INICIA COM A LAMPADA DESLIGADA
		MOV TMOD, #20H		; COLOCA O TIMER 1 EM MODO 2
		MOV TH1, #0FDH		; VALOR DE RECARGA PARA 9600 BITS/S
		MOV IE, #90H		; HABILITA A INTERRUPÇÃO SERIAL
		MOV SCON, #50H		; SERIAL MODO 1 (SM0=0 SM1=1) E REN=1
		SETB TR1		; DISPARA A CONTAGEM DO TIMER 1

MAIN:		MOV DPTR, #MENU
		LCALL SERIAL_WR		; ESCREVE O MENU NA SERIAL E AGUARDA INTERRUPÇÃO
		MOV DPTR, #MSG		; JÁ DEIXA NO DPTR O ENDEREÇO DA MENSAGEM
		SJMP $			; ESPERA AS INTERRUPÇÕES


; =========== SUBROTINA PARA TRATAR A SERIAL =======================
SERIAL:		MOV A, SBUF		; MOVE PARA O ACUMULADOR O VALOR RECEBIDO
		JZ RET1			; VERIFICA SE NÃO RECEBEU NULO
		CJNE A, #, IS_2	; COMPARA SE É 1 (0xH ASCII)
		SETB P2.7		; GIRA O MOTOR DE PASSO
		SJMP RET1

IS_2:		CJNE A, #, IS_3	; COMPARA SE NÃO É 2 (0x4E ASCII)
		CLR P2.7		; DESLIGA A LAMPADA 2
		SJMP RET1

IS_3:		CJNE A, #, IS_4 	; COMPARA SE NÃO É 3 (0X)

		SJMP RET1
		
IS_4:		CJNE A, #, ELSE		; COMPARA SE NÃO É 4 (0X)

		SJMP RET1
		
ELSE:	LCALL SERIAL_WR		; ENVIA MENSAGEM DE ALERTA
RET1:		CLR RI			; RESETA O BIT DE RECEPÇÃO
		RETI

; =========== SUBROTINA PARA ENVIO DE MENSAGENS ====================
SERIAL_WR:	MOV R2, #0
NEXT:		MOV A, R2
		MOVC A, @A+DPTR
		CJNE A, #0FFH, SEND	; DETECTA O CARACTER DE FINAL DE TEXTO
		RET

SEND:		MOV SBUF, A		; INICIA A TRANSMISSÃO DO CARACTER
		JNB TI, $		; AGUARDA TRANSMISSÃO
		CLR TI			; LIMPA FLAG DE TRANSMISSÃO PARA O PROXIMO DADO
		INC R2
		SJMP NEXT		; VAI PARA O PROXIMO MARACTER DA MENSAGEM

; ============ MENSAGENS A SER ENVIADAS =============================
MENU:	DB 'Y - LIGAR LAMPADA', 0DH, 'N - DESLIGAR A LAMPADA', 0DH, 0FFH
MSG:	DB 'DIGITE Y OU N', 0DH, 0FFH
END