ORG 00H
SJMP SETUP

; =========== SUBROTINA PARA CONFIGURAR OS PERIFERICOS =============
ORG 30H
SETUP: 		MOV TMOD, #01H	; TIMER 0 MODO 1 (M10=0 M00=1)
		MOV P1, #01H	; INICIALIZA OS LEDS

MAIN: 		JB P3.0, $	; SEGURA O FLUXO
		LCALL R_LED	; ROTACIONA O LED
		LCALL DELAY	; ATRASO DE 0.5 SEGUNDOS
		SJMP MAIN	; RETORNA 

; =========== SUBROTINA PARA ROTAÇÃO DO LED ========================
R_LED:		MOV A, P1	; RECUPERA A POSIÇÃO DO LED
		RL A		; ROTACIONA ESQUERDA
		MOV P1, A	; ATUALIZA O LED
		RET
; =========== SUBROTINA DE ATRASO ==================================
DELAY:		MOV R0, #72
		SETB TR0		; DISPARA CONTAGEM
RECARGA:	MOV TH0, #0E6H		; RECARRREGA O TIMER
		MOV TL0, #0FFH
		JNB TF0, $		; DT= 6,9444... MS
		CLR TF0
		DJNZ R0, RECARGA	; 72 CONTAGENS DE DT = 0.5 S
		CLR TR0
		RET
END